### ISSUE TITLE
How to install liminix on Linksys E8450 (UBI) with OpenWrt?

### ISSUE THREAD

**Issue by BenediktBroich** [telent/liminix#3]
Do you have a step-by-step guide on how to install liminix on Linksys E8450 (UBI) that is currently running OpenWrt?

**Comment by telent** [comment]
Linksys E8450 support in Liminix is still WIP, so I would probably advise against doing this right now. The closest thing we have to a step-by-step guide is the instructions at https://gti.telent.net/dan/liminix/src/branch/main/modules/outputs/ubimage.nix#L23

**Comment by BenediktBroich** [comment]
Thank you.
